# Generated by Django 2.2.3 on 2019-08-02 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=1000)),
                ('error', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Uploaded at')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
