# Generated by Django 2.2.3 on 2019-08-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationsHistory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='result',
            new_name='ans',
        ),
    ]
