# Generated by Django 2.2.3 on 2019-08-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsHistory', '0002_auto_20190802_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ans',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='error',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
